version: 0.20150918.{build}
image: Visual Studio 2017
configuration: Debug
platform: AnyCPU
shallow_clone: true
clone_folder: c:\IL2CPU

init:
# This option breaks the github link to the build until the build completes.
#  - ps: Update-AppveyorBuild -Version "$(Get-Date -Format yyyy.MM.dd).$env:appveyor_build_number"
    - cmd: git clone https://github.com/CosmosOS/XSharp.git c:\XSharp --depth 1
# This dependency shouldn't exist, but while it exists, we need to clone the Cosmos repo
    - cmd: git clone https://github.com/CosmosOS/Cosmos.git c:\Cosmos --depth 1

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

build_script:
  - cmd: |
      msbuild "..\XSharp\XSharp.sln" /t:Restore /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      msbuild "IL2CPU.sln" /t:Restore;Build /p:Platform="Any CPU" /p:Configuration=Debug /p:DeployExtension=false /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# Disabled for now
#artifacts:
#  - path: 'source\**\*.nupkg'
