version: 0.20150918.{build}
image: Visual Studio 2019
configuration: Debug-CI
platform: Any CPU
shallow_clone: true
clone_folder: c:\IL2CPU

init:
# This option breaks the github link to the build until the build completes.
#  - ps: Update-AppveyorBuild -Version "$(Get-Date -Format yyyy.MM.dd).$env:appveyor_build_number"
# This dependency shouldn't exist, but while it exists, we need to clone the Cosmos repo
    - cmd: |
        git clone https://github.com/CosmosOS/Cosmos.git c:\Cosmos --depth 1
        git clone https://github.com/CosmosOS/XSharp.git c:\XSharp --depth 1

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

build_script:
  - cmd: |
      dotnet build /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: 'artifacts\Debug\nupkg\*.nupkg'
